### ISSUE TITLE
When the template has more than 9 fields i.e. in double digits, the textarea doesn't get printed.

### ISSUE THREAD

**Issue by sbadugu** [kentcdodds/issue-template#34]
![screen shot 2015-03-04 at 6 26 34 pm](https://cloud.githubusercontent.com/assets/10068662/6498063/32fdb138-c29c-11e4-9564-0399d914ec1e.png)

**Comment by sbadugu** [comment]
Actually, this is a better picture. Something goes wrong for double digit fields. Can you guys fix this issue ?
![screen shot 2015-03-04 at 6 38 21 pm](https://cloud.githubusercontent.com/assets/10068662/6498181/bceb1bbe-c29d-11e4-8638-d31b841f5326.png)

**Comment by kentcdodds** [comment]
I was unable to reproduce this issue. I'm not certain that I understand
what's happening. Could you check the console for errors?

-Kent C. Dodds

**Comment by sbadugu** [comment]
May be I wasn't clear enough, let me walk you through again.

When you create a new template, there are fields that you define. If you try to define number of fields to be more than 9 (i.e. field numbers with double digits) and then try to fill your template and create an issue, the fields after 9 don't capture the text you have entered. I can reproduce every single time.


If you carefully see the picture I have uploaded all the fields before 10 have empty text area because I have left empty, but for the fields after 9 I see {{field#}} and not the content from the textarea.

I hope this makes it bit clear. Thanks !

**Comment by kentcdodds** [comment]
@sbadugu, sorry I haven't had a chance to look at this yet. A lot of other things on my plate. Would you be willing to look into a PR?

**Comment by sbadugu** [comment]
Sure, I can look into it. Can you send me location and other details ?

**Comment by kentcdodds** [comment]
The controller and template for this stuff lives in [this folder](https://github.com/kentcdodds/issue-template/tree/master/app/templates)
