### ISSUE TITLE
Is there a way to self-host?  

### ISSUE THREAD

**Issue by cro** [kentcdodds/issue-template#38]
Are there instructions somewhere on self-hosting issue-template?

**Comment by kentcdodds** [comment]
Hey there! There are no instructions... Until now!

- Fork/clone/copy the repo
- Change the firebase URLs (I believe they're just [here](https://github.com/kentcdodds/issue-template/blob/master/app/services/LoginService.js#L2) and [here](https://github.com/kentcdodds/issue-template/blob/master/app/services/TemplateService.js#L2)) to your own. Or, if you don't want to use firebase, you'll have to rework those services a little bit...
- Deploy to whatever server you want that serves up static files
- Profit!

Let me know if you have further questions, but I'm going to go ahead and close this issue for now.

**Comment by cro** [comment]
@kentcdodds, you are awesome.  Thanks for the quick reply.

--cro
