### ISSUE TITLE
This asks for a lot of permissions in my Github account. Why so?

### ISSUE THREAD

**Issue by djowett** [kentcdodds/issue-template#41]

**Comment by kentcdodds** [comment]
Hi @djowett, it's quite possible that I could do something about [the scope](https://github.com/kentcdodds/issue-template/blob/master/app/services/LoginService.js#L27) to make the permissions more reasonable. I'm not certain though. If you'd like to look into it, check out [this file](https://github.com/kentcdodds/issue-template/blob/master/app/services/GitHubService.js) which has all the places where we interface with the GitHub API.

**Comment by RyanCavanaugh** [comment]
Same question here -- I'd be very interested to try this out, but I can't allow this tool to see my Private repos

**Comment by kentcdodds** [comment]
Thanks for your interest in the project! Unfortunately I'm not really working on it much anymore. But I'm happy to discuss solutions and I invite you to [makeapullrequest.com](http://makeapullrequest.com). Thank you for understanding.
