### ISSUE TITLE
How can we edit an existing template?

### ISSUE THREAD

**Issue by mpaiva-pmap** [kentcdodds/issue-template#42]
I need to add new values and fix some typos to an existing template. How can we edit  an existing template?

**Comment by kentcdodds** [comment]
I'm pretty sure there used to be an `Edit` button when you were logged in, but I'm not sure what happened to it. If you'd like to make a PR to add it back, that'd be awesome.

In any case, just add `/edit` to the end of the url for the issue template and you can edit it there.

**Comment by mpaiva-pmap** [comment]
indeed. I'll ask my developer to do a PR to fix that button. Thanks Kent! You can't imagine how much this is helping us. I really appreciate this effort. Cheers!

**Comment by kentcdodds** [comment]
I'm so glad! :D
